apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-dplta
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: train-schedule
          image: tuannanhh/train-schedule:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-svc
spec:
  selector:
    app: nodeapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 30130
